Due to removed ./share/ the autogen.sh & configure were not working anymore. Compiling was not possible. * removed all references of /share from configure.ac and Makefile.am. * configure still failed, added an empty ./share/genbuild.sh to avoid further failing
make failed with: clientversion.cpp:42:10: fatal error: 'build.h' file not found
* commented out #include „build.h“